version: '3'
services:
  app:
    build: .
    image: rb-pinning-service-api:v0.2.0
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - API_ONLY=${API_ONLY}
      - TOKENS_CACHE_TTL=${TOKENS_CACHE_TTL}
      - TOKENS_URL=${TOKENS_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database.service.pinning.internal
      - REDIS_URL=redis://redis.service.pinning.internal
      - IPFS_URL=ipfs.service.pinning.internal
    networks:
      - internal
    depends_on:
      - database.service.pinning.internal
      - redis.service.pinning.internal
      - ipfs.service.pinning.internal

  database.service.pinning.internal:
    image: mysql:8.0.28
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

  redis.service.pinning.internal:
    image: redis:6.2-alpine
    networks:
      - internal

  ipfs.service.pinning.internal:
    image: ipfs/go-ipfs:latest
    networks:
      - internal
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
